"""auto_detect_missing_columns

Revision ID: 460487cc81fd
Revises: 299000097b24
Create Date: 2026-06-16 19:56:56.161508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '460487cc81fd'
down_revision: Union[str, Sequence[str], None] = '299000097b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_faces', 'pose',
               existing_type=postgresql.ENUM('FRONT', 'LEFT', 'RIGHT', 'UP', 'DOWN', 'FRONT_LEFT', 'FRONT_RIGHT', name='facepose'),
               nullable=False)
    op.add_column('users', sa.Column('must_reset_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_reset_password')
    op.alter_column('employee_faces', 'pose',
               existing_type=postgresql.ENUM('FRONT', 'LEFT', 'RIGHT', 'UP', 'DOWN', 'FRONT_LEFT', 'FRONT_RIGHT', name='facepose'),
               nullable=True)
    # ### end Alembic commands ###
