import {
  Paper,
  Typography,
} from "@mui/material";

import { DataGrid } from "@mui/x-data-grid";

import dayjs from "dayjs";

export default function ReportHistoryTable({
  rows,
}: any) {
  const columns = [
    {
      field: "report_name",
      headerName: "Report",
      flex: 1,
    },
    {
      field: "generated_by",
      headerName: "Generated By",
      flex: 1,
    },
    {
      field: "generated_at",
      headerName: "Generated At",
      flex: 1.5,
      renderCell: (params: any) =>
        dayjs(typeof 
          params.value
         === 'string' && !
          params.value
        .endsWith('Z') ? 
          params.value
         + 'Z' : 
          params.value
        ).format(
          "DD-MMM-YYYY hh:mm A"
        ),
    },
    {
      field: "file_url",
      headerName: "File",
      flex: 1,
    },
  ];

  return (
    <Paper sx={{ p: 3 }}>
      <Typography
        variant="h6"
        mb={2}
      >
        Report History
      </Typography>

      <DataGrid
        rows={rows}
        columns={columns}
        autoHeight
        disableRowSelectionOnClick
      />
    </Paper>
  );
}
